4oty: introduce function is-any-of

diff --git a/4oty/4otyrc b/4oty/4otyrc
--- a/4oty/4otyrc
+++ b/4oty/4otyrc
@@ -6,3 +6,13 @@ BIN="${0%/*}"
 function find-data() {
 	find "$DATA" -maxdepth 1 -type f -name '*.tsv'
 }
+
+function is-any-of() {
+	[ -n "$1" ] || return 1
+	local tested="$1"
+	shift
+	for i in "$@" ; do
+		[ "$tested" = "$i" ] && return 0 # success
+	done
+	return 1 # failure
+}
